id: P000727
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137832
  title: རྗེས་དཀར་ཨོ་ཚུལ་གྱི་ལས་འགྲིག་
  author: ''
  volumes:
    d660e7aadb004c348618720a9d5633f3:
      image_group_id: I2PD18700
      title: ''
      volume_number: 1
      total_pages: 574
