id: ID479AE7C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:55:49+00:00'
last_modified: '2022-06-07T13:34:44.908968+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137832
  title: རྗེས་དཀར་ཨོ་ཚུལ་གྱི་ལས་འགྲིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '1396':
      image_group_id: I2PD18700
      title: ''
      total_pages: 574
      order: 1
      base_file: 1396.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
